name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-prod:
    name: '[Prod] Test docker compose'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Prepare config
        # Rebuild the worker image instead of using getindico/indico:latest
        run: |
          cd indico-prod
          pip install yq
          ~/.local/bin/yq '. | .services["indico-web"].build = "./worker"' docker-compose.yml > docker-compose.local.yml

      - name: Build containers
        run: |
          cd indico-prod
          docker compose -f docker-compose.local.yml build

      - name: Test if Indico works
        run: ./test.sh prod

  test-dev:
    name: '[Dev] Test docker compose'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build containers
        run: |
          cd indico-dev
          docker compose build

      - name: Test if Indico works
        run: ./test.sh dev
